{% set name = "hydromt" %}
{% set version = "0.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hydromt-{{ version }}.tar.gz
  sha256: 03b37baf2eb30a5c2d7e7746d84d9ef8ee311f70ab2fe12d9d4ce67c4118eade

build:
  number: 0
  noarch: python
  entry_points:
    - hydromt = hydromt.cli.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python >=3.8
  run:
    - affine
    - bottleneck
    - click
    - dask-core
    - entrypoints
    - gdal >=3.1
    - geopandas >=0.8
    - netcdf4
    - numba
    - numpy
    - openpyxl
    - pandas
    - pyflwdir >=0.4.7
    - pygeos
    - python >=3.8
    - rasterio
    - requests
    - scipy
    - xarray
    - zarr

test:
  imports:
    - hydromt
    - hydromt.cli
  commands:
    - pip check
    - hydromt --help
  requires:
    - pip

about:
  home: https://pypi.org/project/hydromt/
  summary: 'HydroMT: Build and analyze models like a data-wizard!'
  dev_url: https://github.com/Deltares/hydromt
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DirkEilander
    - hboisgon
